services:
  fastapi:
    container_name: fastapi-mock
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
